Unit test now checks if there is a requirements.txt file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,7 +20,7 @@ jobs:
 
     - name: Install dependencies
       run: |
-        pip install -r requirements.txt
+        test -e requirements.txt && echo "requirements.txt found" || echo "requirements.txt not found"
 
     - name: Run unit tests
       run: python -m unittest calculadora_test.py
